settings:
  commit_msg: "chore(readme): refresh blog posts and activity"
  max_lines: 5
  readme_file: "./README.md"

  url_text: "{ID}"

  disabled_events:
    - "push"
    # - "comments"

date:
  text: "Last updated: {DATE}"

  commit_name: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"

messages:
  comments: "ğŸ’¬ Commented on {ID} in {REPO}"
  issue_opened: "â— Opened issue {ID} in {REPO}"
  issue_closed: "âœ”ï¸ Closed issue {ID} in {REPO}"
  pr_opened: "ğŸ’ª Opened PR {ID} in {REPO}"
  pr_closed: "âŒ Closed PR {ID} in {REPO}"
  pr_merged: "ğŸ‰ Merged PR {ID} in {REPO}"
  create_repo: "ğŸ“” Created {REPO}"
  fork_repo: "ğŸ”± Forked {FORK} from {REPO}"
  changes_approved: "ğŸ‘ Approved {ID} in {REPO}"
  changes_requested: "ğŸ”´ Requested changes in {ID} in {REPO}"
  new_release: "âœŒï¸ Released {ID} in {REPO}"
  new_star: "â­ Starred {REPO}"
